apiVersion: v1
kind: Service
metadata:
  name: users-api-node-port
spec:
  type: NodePort
  ports:
    - port: 4041
      targetPort: 4000
      nodePort: 32001
  selector:
    component: users-api-web
