apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: users-api-web
  template:
    metadata:
      labels:
        component: users-api-web
    spec:
      containers:
        - name: client
          image:  guuhworship/users_api
          ports:
            - containerPort: 4000
