apiVersion: v1
kind: Pod
metadata:
  name: users-api-pod
  labels:
    component: users-api-web
spec:
  containers:
    - name: users-api
      image: guuhworship/users_api
      ports:
        - containerPort: 4000
